### ISSUE TITLE
undefined method 'name' in 'champion' factory

### ISSUE THREAD

**Issue by phommata** [dearshrewdwit/rails-api-example#10]
rspec fails on name, I have removed the trait champion and it still fails.

```
bundle exec rspec

An error occurred while loading ./spec/controllers/players_controller_spec.rb.
Failure/Error: name "Roger Federer"

NoMethodError:
  undefined method 'name' in 'champion' factory
```

**Comment by phommata** [comment]
I was able to resolve the issue per: https://github.com/thoughtbot/factory_bot_rails/issues/313#issuecomment-513482207.  Statically defined attributes have been deprecated from factory_bot >= 5.0. And so rather than use statically defined attributes for your factories, use dynamically defined attributes. That is, insert curly brackets {} around every defined attribute in your factory.

Use Dynamically defined attributes
```
FactoryBot.define do
  factory :player do
    trait :champion do
      name { "Roger Federer" }
      age  { "36" }
      prize_money { 110235682 }
      titles { 95 }
      grand_slams { 19 }
    end
  end
end
```

And not statically defined attributes
```
FactoryBot.define do
  factory :player do
    trait :champion do
      name "Roger Federer"
      age  "36"
      prize_money 110235682
      titles 95
      grand_slams 19
    end
  end
end
```

You can read up more about it here
https://thoughtbot.com/blog/deprecating-static-attributes-in-factory_bot-4-11

**Comment by dearshrewdwit** [comment]
Thanks @phommata! Want to open up a PR with the fix?

**Comment by phommata** [comment]
Yes, let me create one.
